"""
Configuration Setup for ParentEye Client
Run this once to configure the client for remote backend connection
"""
import os
import sys
from pathlib import Path

def create_env_file(backend_url=None, mongodb_uri=None):
    """Create or update .env file with configuration"""
    
    env_file = Path(".env")
    
    # Default values
    if not backend_url:
        backend_url = "http://localhost:5000"
    if not mongodb_uri:
        mongodb_uri = "mongodb://localhost:27017/"
    
    env_content = f"""# ParentEye Client Configuration
# This file is auto-generated by config_client.py

# Backend Server URL (where parents access the dashboard)
# IMPORTANT: This must be accessible from the internet
# Examples:
#   Local testing: http://localhost:5000
#   Remote with IP: http://192.168.1.100:5000
#   Remote with domain: http://myserver.com:5000
BACKEND_URL={backend_url}

# MongoDB Connection (Cloud database where data is stored)
# Already configured with MongoDB Atlas (cloud database)
MONGODB_URI={mongodb_uri}

# Database name
DB_NAME=child_monitoring

# Admin Password (set in backend)
ADMIN_PASSWORD=YourSecurePassword123

# Super Admin Password
SUPER_ADMIN_PASSWORD=SuperAdmin@2026

# Flask settings
FLASK_ENV=production
"""
    
    with open(env_file, 'w', encoding='utf-8') as f:
        f.write(env_content)
    
    print(f"✅ Configuration file created: {env_file}")
    return True

def setup_wizard():
    """Interactive setup wizard"""
    print("\n" + "="*60)
    print("🚀 ParentEye Client Configuration Setup")
    print("="*60)
    
    print("\n📝 This setup will configure your client to connect to the backend server.")
    print("Parents will monitor this PC through the web dashboard.\n")
    
    # Get backend URL
    print("Step 1: Backend Server URL")
    print("-" * 40)
    print("Enter the backend server address:")
    print("  Examples:")
    print("    • Local: http://localhost:5000")
    print("    • Network: http://192.168.1.100:5000")
    print("    • Domain: http://myserver.example.com:5000")
    print("    • HTTPS: https://myserver.example.com")
    
    backend_url = input("\nBackend URL [http://localhost:5000]: ").strip()
    if not backend_url:
        backend_url = "http://localhost:5000"
    
    # Validate URL
    if not backend_url.startswith(('http://', 'https://')):
        backend_url = "http://" + backend_url
    
    print(f"✅ Backend URL set to: {backend_url}")
    
    # Get MongoDB connection (skip - use cloud default)
    print("\n\nStep 2: Database Configuration")
    print("-" * 40)
    print("Your system is configured to use MongoDB Atlas (cloud database).")
    print("This allows data to be stored securely in the cloud.")
    mongodb_uri = "mongodb+srv://darpanmeher1346_db_user:luF1dnvrUsL0ZIUI@main.utpopfr.mongodb.net/?appName=main"
    
    print(f"✅ Database: MongoDB Atlas (Cloud)")
    
    # Create the .env file
    print("\n\nStep 3: Creating Configuration")
    print("-" * 40)
    create_env_file(backend_url, mongodb_uri)
    
    print("\n" + "="*60)
    print("✅ Configuration Complete!")
    print("="*60)
    print("\n📋 Summary:")
    print(f"  Backend Server: {backend_url}")
    print("  Database: MongoDB Atlas (Cloud)")
    print("  Config File: .env")
    
    print("\n🔧 Next Steps:")
    print("  1. Run: python run_client_as_admin.bat")
    print("     (This ensures admin privileges for website/app blocking)")
    print("  2. To build EXE: pyinstaller ParentEye_Client.spec")
    print("  3. Distribute the EXE to child PCs")
    
    print("\n⚠️  IMPORTANT NOTES:")
    print("  • The backend must be accessible from child PCs")
    print("  • If using a domain, make sure it's configured correctly")
    print("  • Child PCs must be able to reach the backend server")
    print("  • Requires admin rights to run (for blocking/monitoring)")
    
    print("\n")

if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--wizard":
        setup_wizard()
    else:
        # Default setup
        create_env_file()
        setup_wizard()
